server:
  port: 8082

spring:
  application:
    name: product-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://mysql-product:3306/productdb   # Matches service name in docker-compose.prod.yml
    username: root
    password: root  # Use the production DB password defined in docker-compose
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka   # Eureka container in Docker
  instance:
    prefer-ip-address: true
