name: Deploy to EC2

on:
  push:
    branches: [main]  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -t user-service:latest -f user-service/Dockerfile ./user-service
          docker build -t product-service:latest -f product-service/Dockerfile ./product-service
          docker build -t order-service:latest -f order-service/Dockerfile ./order-service
          docker build -t notification-service:latest -f notification-service/Dockerfile ./notification-service
          docker build -t eureka-server:latest -f eureka-server/Dockerfile ./eureka-server
          docker save user-service:latest > user-service.tar
          docker save product-service:latest > product-service.tar
          docker save order-service:latest > order-service.tar
          docker save notification-service:latest > notification-service.tar
          docker save eureka-server:latest > eureka-server.tar

      - name: Copy Docker images and compose file to EC2
        run: |
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" \
            user-service.tar product-service.tar order-service.tar notification-service.tar eureka-server.tar docker-compose.yml \
            ${{ secrets.EC2_HOST }}:/home/ec2-user/InventoryMangementProject/

      - name: Load images and deploy on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/InventoryMangementProject

            # Check if Maven is installed, install if missing
            if ! command -v mvn &> /dev/null
            then
              echo "Maven not found. Installing Maven..."
              sudo yum install -y maven
            fi

            echo "Loading Docker images..."
            docker load -i user-service.tar
            docker load -i product-service.tar
            docker load -i order-service.tar
            docker load -i notification-service.tar
            docker load -i eureka-server.tar

            echo "Restarting Docker containers..."
            docker-compose down
            docker-compose up -d
          EOF
